### ISSUE TITLE
how to show the pdf which has  chineses font

### ISSUE THREAD

**Issue by zww7821270** [hrynko/vue-pdf-embed#42] opened 2022-06-06 13:59 UTC
I make a pdf, use vue-pdf-embed in vue3 project ,it can not show the pdf which has chineses well, chineses font are all lost.

**Comment by hrynko** [comment] 2022-06-07 22:49
Hi @zww7821270,

Could you provide a sample PDF that you are having issues with? So far, I haven't noticed any problems when displaying documents containing Chinese characters.

**Comment by zww7821270** [comment] 2022-06-08 01:39
I send two files, template6.pdf is the template which does not has the values , it is only PDF form input fileds,I use JAVA itext to set values into the form input fileds for make 2206110100101.pdf；
then I use our vue-pdf-embed to show the 2206110100101.pdf, it does not show the value that I set to the input fields, so I create the issus for your help , thank you
&nbsp;(I am not sure if I explained it&nbsp; clearly)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hrynko/vue-pdf-embed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月8日(星期三) 上午6:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hrynko/vue-pdf-embed] how to show the pdf which has  chineses font (Issue #42)





 
Hi @zww7821270,
 
Could you provide a sample PDF that you are having issues with? So far, I haven't noticed any problems when displaying documents containing Chinese characters.

**Comment by zww7821270** [comment] 2022-06-08 01:40
ok， I sended to your email，please find

**Comment by hrynko** [comment] 2022-06-08 14:46
I couldn't find the message with sample files. But it seems that the problem is the lack of input data, not the display of Chinese characters, right?

**Comment by hrynko** [comment] 2022-06-08 14:47
Can you post your anonymized sample files here in `base64`?

**Comment by sea-caterpillar** [comment] 2022-06-13 02:46
I have the same issue in Chromium;
`"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3405.0 Safari/537.36"`

![image](https://user-images.githubusercontent.com/25836014/173270363-7abac861-2f52-49c6-88fb-bd57741db9dc.png)

[template.pdf](https://github.com/hrynko/vue-pdf-embed/files/8887546/template.pdf)

**Comment by hrynko** [comment] 2022-06-13 10:24
Hi @sea-caterpillar,

Thank you for the sample file, I will check the problem.

**Comment by hrynko** [comment] 2022-06-14 09:24
I checked the provided file and couldn't reproduce the issue. Please see [Fiddle](https://jsfiddle.net/hrynko/5n2ycpt8/).

Could you provide more details on which environment/versions you are using? Or maybe provide a JSFiddle/Codesandbox/etc to demonstrate the issue?

**Comment by sea-caterpillar** [comment] 2022-06-14 10:04
@hrynko 
The problem still exists using your example；

![image](https://user-images.githubusercontent.com/25836014/173549279-9720a2f0-d632-4046-91ab-fbddc6ca83be.png)

Browsers version
`"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3405.0 Safari/537.36"`

**Comment by hrynko** [comment] 2022-06-14 10:56
Hmm, looks very browser/system specific. I tried a few but could never reproduce. Do you experience any font issues outside the library?

**Comment by sea-caterpillar** [comment] 2022-06-15 09:42
>  Do you experience any font issues outside the library? 

No;

But I  found the `Word to PDF` applications affected me;
WPS Office: ❌
PDF Candy: ✔

**Comment by hrynko** [comment] 2022-06-15 12:55
Sorry, I don't get it. What do you mean by "affecting" you?

**Comment by sea-caterpillar** [comment] 2022-06-16 00:49
Under the same browser version,  the fonts of PDF files exported by WPS Office will be lost, but the fonts of PDF files exported by PDF Candy are normal.
I found it by accident. I don't know why.

[bad.pdf](https://github.com/hrynko/vue-pdf-embed/files/8914634/bad.pdf)
[good.pdf](https://github.com/hrynko/vue-pdf-embed/files/8914635/good.pdf)

**Comment by hrynko** [comment] 2022-06-16 07:24
I don't know why either 🙂

I have both documents displayed without any problems

**Comment by sea-caterpillar** [comment] 2022-06-16 07:39
Thank you for your reply, I will check the reason later

**Comment by hrynko** [comment] 2022-07-04 10:55
Hi @sea-caterpillar,

I'm closing the issue as it is not clear if anything needs to be fixed there, although I would appreciate if you reopen it when you have more details, thanks.

**Closed by hrynko** 2022-07-04 10:55 UTC
