### ISSUE TITLE
Xiaomi's MIUI 12.X App crashes after rendering more than 10 pages of PDF at a time.

### ISSUE THREAD

**Issue by ZmonGitHub** [hrynko/vue-pdf-embed#118] opened 2023-02-20 06:32 UTC

**Comment by hrynko** [comment] 2023-02-22 14:00
Hi @ZmonGitHub,

Thanks for opening the issue. Right now it is quite difficult to find out the cause from this description, but it can be useful in the future.

**Comment by hrynko** [comment] 2024-01-20 14:08
After several memory usage optimzations and a switch to Vite, this may already be resolved in `v2.0.0`

**Closed by hrynko** 2024-01-20 14:08 UTC
