### ISSUE TITLE
examples do not work in firefox

### ISSUE THREAD

**Issue by i-am-xhy** [hrynko/vue-pdf-embed#13] opened 2022-03-08 12:47 UTC
While the examples work under chromium/webkit, they do not work under firefox.
This partially translates to them not working in real conditions.
Under firefox the pdf does seem to load extremely slowly, but i have not witnessed it triggering rendered, prohibiting any sort of loading implementation

**Comment by hrynko** [comment] 2022-03-08 14:10
Could you describe your environment and what kind of issues you are experiencing? So far I haven't been able to reproduce this in Firefox.

**Comment by i-am-xhy** [comment] 2022-03-08 14:33
If i open the jsfiddles you have given under examples, under chromium they work fine while under firefox version 91.6.1esr (64-bit) it doesn't.

The slow loading is for the same version. i suspect may have something to do with my usage of the esr version, but i am currently unable to test on a different version. So i'll get back to you once i have had the chance to do that.

**Comment by hrynko** [comment] 2022-03-10 08:26
Ok, I guess there should be some of the failure events emitted then (`loading-failed` or `rendering-failed`). Can you log them to the console and provide the output?

**Comment by i-am-xhy** [comment] 2022-03-11 13:50
The events never trigger (in jsfiddle), I am still looking into what is actually going on. But it may be monday before i am able to commit further time to investigating.

The problem does seem to have been eliminated for Firefox, so i assume it was something in their most recent version, or maybe a config somewhere.

**Comment by hrynko** [comment] 2022-03-30 09:58
I tested the library in Firefox 98.0 running on Windows 10 (64-bit), and I was unable to reproduce the issue. It worked just as in other environments.

Perhaps there was the same problem as in Safari (#14). A fix for it has been released in `1.1.1`. And I hope it fixes this problem as well. Otherwise, please reopen the issue. Thanks!

**Closed by hrynko** 2022-03-30 09:58 UTC
