### ISSUE TITLE
'scale' parameter causes view is not clear

### ISSUE THREAD

**Issue by jojo-d** [hrynko/vue-pdf-embed#106] opened 2022-12-28 02:49 UTC

**Comment by brocard** [comment] 2023-02-08 14:39
Yes i saw the same issue with scale parameter, the pdf turn blurred, i can share example if you want?

**Comment by hrynko** [comment] 2023-02-08 14:42
Hi @brocard, yes please, it would be very helpful

**Comment by hrynko** [comment] 2023-02-16 20:04
Well, I assume it may be a duplicate of https://github.com/hrynko/vue-pdf-embed/issues/93#issuecomment-1328030286. Please see the linked comment and feel free to reopen the issue if it isn't the case.

**Closed by hrynko** 2023-02-16 20:04 UTC
